version: '3.8'
services:
    myapp:
        build:
            context: ./
            dockerfile: ./Dockerfile.local
        image: myapp
        platform: linux/amd64
        ports: 
          - '9000:9000'
        volumes:
            - .:/app/
        depends_on:
            mssql:
                condition: service_healthy

    mssql:
        container_name: myapp_mssql
        build:
            context: ./
            dockerfile: ./Dockerfile.mssql
        image: mssql
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=strongPasswordMSSQL123
        volumes:
            - myapp:/var/opt/mssql
        ports:
            - '1433:1433'
        healthcheck:
            test: "exit 0"
volumes:
    myapp:
